// Code generated by protoc-gen-go. DO NOT EDIT.
// source: counter.proto

/*
Package count is a generated protocol buffer package.

It is generated from these files:
	counter.proto

It has these top-level messages:
	Value
	SettingsRequest
	SettingsReply
*/
package count

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Counter value
type Value struct {
	Value int64 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Value) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// Settings to change
type SettingsRequest struct {
	Step  int64 `protobuf:"varint,1,opt,name=step" json:"step,omitempty"`
	Limit int64 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
}

func (m *SettingsRequest) Reset()                    { *m = SettingsRequest{} }
func (m *SettingsRequest) String() string            { return proto.CompactTextString(m) }
func (*SettingsRequest) ProtoMessage()               {}
func (*SettingsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SettingsRequest) GetStep() int64 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *SettingsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

// The response message containing settings change status
type SettingsReply struct {
	Code    int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *SettingsReply) Reset()                    { *m = SettingsReply{} }
func (m *SettingsReply) String() string            { return proto.CompactTextString(m) }
func (*SettingsReply) ProtoMessage()               {}
func (*SettingsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SettingsReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SettingsReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Value)(nil), "count.Value")
	proto.RegisterType((*SettingsRequest)(nil), "count.SettingsRequest")
	proto.RegisterType((*SettingsReply)(nil), "count.SettingsReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Counter service

type CounterClient interface {
	// Works with counter
	GetNumber(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Value, error)
	IncrementNumber(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	SetSettings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*SettingsReply, error)
}

type counterClient struct {
	cc *grpc.ClientConn
}

func NewCounterClient(cc *grpc.ClientConn) CounterClient {
	return &counterClient{cc}
}

func (c *counterClient) GetNumber(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := grpc.Invoke(ctx, "/count.Counter/GetNumber", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counterClient) IncrementNumber(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/count.Counter/IncrementNumber", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counterClient) SetSettings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*SettingsReply, error) {
	out := new(SettingsReply)
	err := grpc.Invoke(ctx, "/count.Counter/SetSettings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Counter service

type CounterServer interface {
	// Works with counter
	GetNumber(context.Context, *google_protobuf.Empty) (*Value, error)
	IncrementNumber(context.Context, *google_protobuf.Empty) (*google_protobuf.Empty, error)
	SetSettings(context.Context, *SettingsRequest) (*SettingsReply, error)
}

func RegisterCounterServer(s *grpc.Server, srv CounterServer) {
	s.RegisterService(&_Counter_serviceDesc, srv)
}

func _Counter_GetNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServer).GetNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/count.Counter/GetNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServer).GetNumber(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Counter_IncrementNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServer).IncrementNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/count.Counter/IncrementNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServer).IncrementNumber(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Counter_SetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServer).SetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/count.Counter/SetSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServer).SetSettings(ctx, req.(*SettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Counter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "count.Counter",
	HandlerType: (*CounterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNumber",
			Handler:    _Counter_GetNumber_Handler,
		},
		{
			MethodName: "IncrementNumber",
			Handler:    _Counter_IncrementNumber_Handler,
		},
		{
			MethodName: "SetSettings",
			Handler:    _Counter_SetSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "counter.proto",
}

func init() { proto.RegisterFile("counter.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x13, 0x35, 0x96, 0x8e, 0x2d, 0x85, 0xb5, 0x94, 0x10, 0x11, 0x64, 0x41, 0xf0, 0xb4,
	0x05, 0x7b, 0x94, 0x5e, 0x5a, 0x44, 0xbc, 0x48, 0x49, 0xc1, 0x7b, 0x12, 0xc7, 0x10, 0xdc, 0xcd,
	0xc6, 0x64, 0x52, 0xcc, 0xeb, 0xf9, 0x64, 0xb2, 0xbb, 0x09, 0x82, 0x22, 0xde, 0xe6, 0x1f, 0xe6,
	0xe3, 0xe7, 0xdb, 0x85, 0x69, 0xa6, 0xdb, 0x92, 0xb0, 0x16, 0x55, 0xad, 0x49, 0xb3, 0xc0, 0xc6,
	0xe8, 0x22, 0xd7, 0x3a, 0x97, 0xb8, 0xb4, 0xcb, 0xb4, 0x7d, 0x5d, 0xa2, 0xaa, 0xa8, 0x73, 0x37,
	0xfc, 0x12, 0x82, 0xe7, 0x44, 0xb6, 0xc8, 0xe6, 0x10, 0x1c, 0xcc, 0x10, 0xfa, 0x57, 0xfe, 0xcd,
	0x71, 0xec, 0x02, 0xbf, 0x83, 0xd9, 0x1e, 0x89, 0x8a, 0x32, 0x6f, 0x62, 0x7c, 0x6f, 0xb1, 0x21,
	0xc6, 0xe0, 0xa4, 0x21, 0xac, 0xfa, 0x3b, 0x3b, 0x1b, 0x58, 0x16, 0xaa, 0xa0, 0xf0, 0xc8, 0xc1,
	0x36, 0xf0, 0x35, 0x4c, 0xbf, 0xe1, 0x4a, 0x76, 0x06, 0xcd, 0xf4, 0x8b, 0xab, 0x08, 0x62, 0x3b,
	0xb3, 0x10, 0x46, 0x0a, 0x9b, 0x26, 0xc9, 0xd1, 0xc2, 0xe3, 0x78, 0x88, 0xb7, 0x9f, 0x3e, 0x8c,
	0xb6, 0x4e, 0x88, 0xad, 0x60, 0xfc, 0x80, 0xf4, 0xd4, 0xaa, 0x14, 0x6b, 0xb6, 0x10, 0xce, 0x48,
	0x0c, 0x46, 0xe2, 0xde, 0x18, 0x45, 0x13, 0x61, 0x85, 0x85, 0x15, 0xe2, 0x1e, 0xdb, 0xc2, 0xec,
	0xb1, 0xcc, 0x6a, 0x54, 0x58, 0xfe, 0x87, 0xfe, 0xb1, 0xe7, 0x1e, 0x5b, 0xc3, 0xd9, 0x1e, 0x69,
	0xf0, 0x60, 0x8b, 0xbe, 0xe3, 0xc7, 0xab, 0x44, 0xf3, 0x5f, 0xfb, 0x4a, 0x76, 0xdc, 0xdb, 0x5c,
	0xc3, 0xb9, 0xc4, 0x37, 0x7d, 0xa8, 0x05, 0x7e, 0x24, 0x4a, 0xf4, 0x1f, 0xb4, 0x99, 0xf4, 0x62,
	0x3b, 0x53, 0xb7, 0xf3, 0xd3, 0x53, 0xdb, 0xbb, 0xfa, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x2d,
	0x25, 0x81, 0xc2, 0x01, 0x00, 0x00,
}
