// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: counter.proto

/*
Package counter is a generated protocol buffer package.

It is generated from these files:
	counter.proto

It has these top-level messages:
	Number
	SettingsRequest
	SettingsReply
*/
package counter

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Counter value
type Number struct {
	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (m *Number) Reset()                    { *m = Number{} }
func (m *Number) String() string            { return proto.CompactTextString(m) }
func (*Number) ProtoMessage()               {}
func (*Number) Descriptor() ([]byte, []int) { return fileDescriptorCounter, []int{0} }

func (m *Number) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

// Settings to change
type SettingsRequest struct {
	Step  int64 `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"`
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (m *SettingsRequest) Reset()                    { *m = SettingsRequest{} }
func (m *SettingsRequest) String() string            { return proto.CompactTextString(m) }
func (*SettingsRequest) ProtoMessage()               {}
func (*SettingsRequest) Descriptor() ([]byte, []int) { return fileDescriptorCounter, []int{1} }

func (m *SettingsRequest) GetStep() int64 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *SettingsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

// The response message containing settings change status
type SettingsReply struct {
	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *SettingsReply) Reset()                    { *m = SettingsReply{} }
func (m *SettingsReply) String() string            { return proto.CompactTextString(m) }
func (*SettingsReply) ProtoMessage()               {}
func (*SettingsReply) Descriptor() ([]byte, []int) { return fileDescriptorCounter, []int{2} }

func (m *SettingsReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SettingsReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Number)(nil), "counter.Number")
	proto.RegisterType((*SettingsRequest)(nil), "counter.SettingsRequest")
	proto.RegisterType((*SettingsReply)(nil), "counter.SettingsReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Counter service

type CounterClient interface {
	// Works with counter
	GetNumber(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Number, error)
	IncrementNumber(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	SetSettings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*SettingsReply, error)
}

type counterClient struct {
	cc *grpc.ClientConn
}

func NewCounterClient(cc *grpc.ClientConn) CounterClient {
	return &counterClient{cc}
}

func (c *counterClient) GetNumber(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Number, error) {
	out := new(Number)
	err := grpc.Invoke(ctx, "/counter.Counter/GetNumber", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counterClient) IncrementNumber(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/counter.Counter/IncrementNumber", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counterClient) SetSettings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*SettingsReply, error) {
	out := new(SettingsReply)
	err := grpc.Invoke(ctx, "/counter.Counter/SetSettings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Counter service

type CounterServer interface {
	// Works with counter
	GetNumber(context.Context, *google_protobuf.Empty) (*Number, error)
	IncrementNumber(context.Context, *google_protobuf.Empty) (*google_protobuf.Empty, error)
	SetSettings(context.Context, *SettingsRequest) (*SettingsReply, error)
}

func RegisterCounterServer(s *grpc.Server, srv CounterServer) {
	s.RegisterService(&_Counter_serviceDesc, srv)
}

func _Counter_GetNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServer).GetNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/counter.Counter/GetNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServer).GetNumber(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Counter_IncrementNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServer).IncrementNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/counter.Counter/IncrementNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServer).IncrementNumber(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Counter_SetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServer).SetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/counter.Counter/SetSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServer).SetSettings(ctx, req.(*SettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Counter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "counter.Counter",
	HandlerType: (*CounterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNumber",
			Handler:    _Counter_GetNumber_Handler,
		},
		{
			MethodName: "IncrementNumber",
			Handler:    _Counter_IncrementNumber_Handler,
		},
		{
			MethodName: "SetSettings",
			Handler:    _Counter_SetSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "counter.proto",
}

func init() { proto.RegisterFile("counter.proto", fileDescriptorCounter) }

var fileDescriptorCounter = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x13, 0xb5, 0x09, 0x1d, 0x29, 0x81, 0x41, 0x4a, 0x88, 0x97, 0xb2, 0x27, 0x4f, 0x29,
	0x28, 0x78, 0x11, 0x0f, 0x52, 0x44, 0xbc, 0x78, 0x48, 0x3f, 0x81, 0x89, 0x63, 0x08, 0x64, 0xff,
	0x98, 0x9d, 0x1c, 0xf2, 0x11, 0xfd, 0x56, 0xd2, 0xdd, 0xac, 0x82, 0x28, 0xbd, 0xcd, 0x7b, 0xfb,
	0xde, 0xee, 0xfe, 0x06, 0x56, 0x8d, 0x1e, 0x15, 0xd3, 0x50, 0x9a, 0x41, 0xb3, 0xc6, 0x74, 0x96,
	0xc5, 0x65, 0xab, 0x75, 0xdb, 0xd3, 0xd6, 0xd9, 0xf5, 0xf8, 0xbe, 0x25, 0x69, 0x78, 0xf2, 0x29,
	0xb1, 0x81, 0xe4, 0x65, 0x94, 0x35, 0x0d, 0xb8, 0x86, 0x44, 0xb9, 0x29, 0x8f, 0x37, 0xf1, 0xd5,
	0x69, 0x35, 0x2b, 0x71, 0x07, 0xd9, 0x9e, 0x98, 0x3b, 0xd5, 0xda, 0x8a, 0x3e, 0x46, 0xb2, 0x8c,
	0x08, 0x67, 0x96, 0xc9, 0xcc, 0x41, 0x37, 0xe3, 0x05, 0x2c, 0xfa, 0x4e, 0x76, 0x9c, 0x9f, 0x38,
	0xd3, 0x0b, 0x71, 0x0f, 0xab, 0x9f, 0xb2, 0xe9, 0xa7, 0x43, 0xb5, 0xd1, 0x6f, 0xe4, 0xaa, 0x8b,
	0xca, 0xcd, 0x98, 0x43, 0x2a, 0xc9, 0xda, 0xd7, 0x96, 0x5c, 0x79, 0x59, 0x05, 0x79, 0xfd, 0x19,
	0x43, 0xba, 0xf3, 0x18, 0x78, 0x0b, 0xcb, 0x27, 0xe2, 0xf0, 0xd9, 0xd2, 0x43, 0x95, 0x01, 0xaa,
	0x7c, 0x3c, 0x40, 0x15, 0x59, 0x19, 0x96, 0xe0, 0x83, 0x22, 0xc2, 0x1d, 0x64, 0xcf, 0xaa, 0x19,
	0x48, 0x92, 0x3a, 0xd6, 0xfe, 0xc7, 0x17, 0x11, 0x3e, 0xc0, 0xf9, 0x9e, 0x38, 0xa0, 0x60, 0xfe,
	0xfd, 0xcc, 0xaf, 0xd5, 0x14, 0xeb, 0x3f, 0x4e, 0x4c, 0x3f, 0x89, 0xa8, 0x4e, 0xdc, 0xa5, 0x37,
	0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xc7, 0x4e, 0x86, 0xa7, 0x01, 0x00, 0x00,
}
